name: dartrix
version: 0.0.1
description: A Linear Algebra practice site written in Dart
author: Alexander Pavel <alexpavel123@gmail.com>
homepage: https://github.com/AlexNPavel/dartrix
environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  polymer_elements: ^1.0.0-rc.8
  polymer: ^1.0.0-rc.15
  web_components: ^0.12.0

transformers:
- polymer:
    entry_points: web/index.html
- $dart2js:
    minify: false
- dart_to_js_script_rewriter
