name: dartrix
version: 0.0.1
description: A Linear Algebra practice site written in Dart
author: Alexander Pavel <alexpavel123@gmail.com>
homepage: https://github.com/AlexNPavel/dartrix
environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  browser: ^0.10.0+2
  dart_to_js_script_rewriter: ^1.0.1
  polymer_elements: ^1.0.0-rc.9
  polymer: ^1.0.0-rc.18
  web_components: ^0.12.3

transformers:
- polymer:
    entry_points: web/index.html
- $dart2js:
    minify: true
    checked: false
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
- dart_to_js_script_rewriter
