name: dartrix
version: 0.0.1
description: A Linear Algebra practice site written in Dart
author: Alexander Pavel <alexpavel123@gmail.com>
homepage: https://github.com/AlexNPavel/dartrix
environment:
  sdk: '>=1.16.0 <2.0.0'
dependencies:
  dart_to_js_script_rewriter: ^1.0.1
transformers:
- dart_to_js_script_rewriter
